name: PHPUnit Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-phpunit:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml
          coverage: none

      # 3. Install dependency Composer (termasuk PHPUnit)
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

     # 4. Cek apakah API_KEY tersedia (AMAN)
      - name: Check APIKEY
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: |
          if [ -z "$APIKEY" ]; then
            echo "❌ APIKEY tidak ditemukan"
            exit 1
          else
            echo "✅ APIKEY tersedia"
          fi

      # 5. Jalankan file PHP
      - name: Run PHP script
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: |
          php api.php
